### ISSUE TITLE
PropTypes warning with React 15

### ISSUE THREAD

**Issue by virzen** [zth/enzyme-async-helpers#1]
When used with React 15, any of the methods causes 
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```
warning to appear.

This is probably caused by [this line](https://github.com/zth/enzyme-async-helpers/blob/master/src/wait.js#L2), which imports everything from the React package, including `PropTypes` in case of React < 16.

Assuming that import is used to get `React` and types from the `react` package, I think it might be split into separate declarations:
```
import React from 'react';
import type * from 'react';
```
I don't know Flow very well though, so this might not be true.

While I realize this package isn't necessarily meant to work with React < 16, if the above is only thing required to make it compatible, I think it's worth doing it.

**Comment by virzen** [comment]
Actually, replacing the `import *` with `import React` seems to suffice (tests and Flow are passing). I've created a PR doing just that. ☝️

**Comment by zth** [comment]
Ah, nice catch, that's great! I'll go ahead and merge your PR tomorrow night. Thanks!

**Comment by zth** [comment]
This is now shipped, thanks again for your help!

**Comment by virzen** [comment]
Glad I could be of help. 😄
